/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.koneksi;
import Model.user_model;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Wien Nurul Dewani
 */
public class daftar3 extends javax.swing.JFrame {

    /**
     * Creates new form daftar3
     */
    public daftar3() {
        initComponents();
    }
    
   
    
     String getGender(){
        if(lkbutton.isSelected())
    {
        return "Laki-laki";
    }
    else if(prbutton.isSelected())
    {
        return "Perempuan";
    }
    else
    {
        return null;
    }

    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernametxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonDaftar = new javax.swing.JButton();
        namatxt = new javax.swing.JTextField();
        buttonInputData1 = new javax.swing.JButton();
        emailtxt = new javax.swing.JTextField();
        nohptxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prbutton = new javax.swing.JRadioButton();
        lkbutton = new javax.swing.JRadioButton();
        ttltxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamattxt = new javax.swing.JTextArea();
        provinsitxt = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kotatxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernametxt1 = new javax.swing.JTextField();
        passwordtxt1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buttonDaftar1 = new javax.swing.JButton();
        namatxt1 = new javax.swing.JTextField();
        buttonInputData2 = new javax.swing.JButton();
        emailtxt1 = new javax.swing.JTextField();
        nohptxt1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ttltxt1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamattxt1 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        kotatxt1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        provinsitxt1 = new javax.swing.JTextField();
        jktxt = new javax.swing.JTextField();

        usernametxt.setToolTipText("");
        usernametxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(150, 203, 61))); // NOI18N

        passwordtxt.setToolTipText("");
        passwordtxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(150, 203, 61))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel12.setText("Email");

        jLabel4.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel4.setText("No. Telp");

        buttonDaftar.setBackground(new java.awt.Color(255, 255, 255));
        buttonDaftar.setText("Daftar");

        namatxt.setToolTipText("");
        namatxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(150, 203, 61))); // NOI18N

        buttonInputData1.setBackground(new java.awt.Color(255, 255, 255));
        buttonInputData1.setText("Batal");

        emailtxt.setToolTipText("");
        emailtxt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        nohptxt.setToolTipText("");
        nohptxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(150, 203, 61))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jLabel6.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel6.setText("Alamat Lengkap");

        jLabel7.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel7.setText("Tempat, Tanggal Lahir");

        prbutton.setBackground(new java.awt.Color(255, 255, 255));
        prbutton.setFont(new java.awt.Font("Keep Calm Med", 0, 10)); // NOI18N
        prbutton.setText("Perempuan");

        lkbutton.setBackground(new java.awt.Color(255, 255, 255));
        lkbutton.setFont(new java.awt.Font("Keep Calm Med", 0, 10)); // NOI18N
        lkbutton.setText("Laki-Laki");

        ttltxt.setToolTipText("");
        ttltxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(150, 203, 61))); // NOI18N

        alamattxt.setColumns(20);
        alamattxt.setRows(5);
        alamattxt.setTabSize(5);
        alamattxt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane1.setViewportView(alamattxt);

        provinsitxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel8.setText("Provinsi");

        jLabel9.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel9.setText("Kota");

        kotatxt.setToolTipText("");
        kotatxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(150, 203, 61))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel10.setText("Username");

        jLabel11.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel11.setText("Password");

        jLabel2.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel2.setText("Nama");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernametxt1.setToolTipText("");
        usernametxt1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(150, 203, 61))); // NOI18N

        passwordtxt1.setToolTipText("");
        passwordtxt1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(150, 203, 61))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel13.setText("Email");

        jLabel14.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel14.setText("No. Telp");

        buttonDaftar1.setBackground(new java.awt.Color(255, 255, 255));
        buttonDaftar1.setText("Daftar");
        buttonDaftar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDaftar1ActionPerformed(evt);
            }
        });

        namatxt1.setToolTipText("");
        namatxt1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(150, 203, 61))); // NOI18N

        buttonInputData2.setBackground(new java.awt.Color(255, 255, 255));
        buttonInputData2.setText("Batal");

        emailtxt1.setToolTipText("");
        emailtxt1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        nohptxt1.setToolTipText("");
        nohptxt1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(150, 203, 61))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel15.setText("Jenis Kelamin");

        jLabel16.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel16.setText("Alamat Lengkap");

        jLabel17.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel17.setText("Tempat, Tanggal Lahir");

        ttltxt1.setToolTipText("");
        ttltxt1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(150, 203, 61))); // NOI18N

        alamattxt1.setColumns(20);
        alamattxt1.setRows(5);
        alamattxt1.setTabSize(5);
        alamattxt1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane2.setViewportView(alamattxt1);

        jLabel18.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel18.setText("Provinsi");

        jLabel19.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel19.setText("Kota");

        kotatxt1.setToolTipText("");
        kotatxt1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(150, 203, 61))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel20.setText("Username");

        jLabel21.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel21.setText("Password");

        jLabel3.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel3.setText("Nama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(provinsitxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(565, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel3)
                                            .addComponent(namatxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(74, 74, 74)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel19)
                                                        .addComponent(kotatxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(129, 129, 129))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel13)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(emailtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(80, 80, 80))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(161, 161, 161)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel14)
                                            .addComponent(nohptxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jLabel17)
                                    .addComponent(ttltxt1))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21))
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(usernametxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(184, 184, 184)
                                    .addComponent(buttonDaftar1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(passwordtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonInputData2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(provinsitxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ttltxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(emailtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(namatxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(33, 33, 33)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nohptxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kotatxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel18)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(49, 49, 49)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(usernametxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonDaftar1))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(passwordtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonInputData2))
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDaftar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDaftar1ActionPerformed
        // TODO add your handling code here:
        
        user_model us = new user_model();
        us.setNama(namatxt1.getText());
        us.setUsername(usernametxt1.getText());
        us.setPassword(passwordtxt1.getText());
        us.setAlamat(alamattxt1.getText());
        us.setEmail(emailtxt1.getText());
        us.setJeniskelamin(jktxt.getText());
        us.setProvinsi(provinsitxt1.getText());
         us.setTtl(ttltxt1.getText());
        us.setKota(kotatxt1.getText());
        us.setNohp(nohptxt1.getText());
        
        try {
            String sql = "INSERT INTO `user baru`(`username`, `password`, `no hp`, `alamat`, `nama`, `provinsi`, `kota`, `email`, `jenis kelamin`, `ttl`) VALUES ('" + us.getNama()
                    + "','" + us.getPassword()+ "','" + us.getNohp()+"','" + us.getAlamat()+"','" + us.getNama()+"','" + us.getProvinsi()
                            +"','" + us.getKota()+"','" + us.getEmail()+"','" + us.getJeniskelamin()+"','" + us.getTtl()+"')";
            java.sql.Connection conn = (Connection) koneksi.connectDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Anda telah terdaftar");
           

        } catch (Exception e) {

        }
        
        dispose();
        Menunew obj = new Menunew();
        obj.setVisible(true);
    }//GEN-LAST:event_buttonDaftar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftar3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamattxt;
    private javax.swing.JTextArea alamattxt1;
    private javax.swing.JButton buttonDaftar;
    private javax.swing.JButton buttonDaftar1;
    private javax.swing.JButton buttonInputData1;
    private javax.swing.JButton buttonInputData2;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField emailtxt1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jktxt;
    private javax.swing.JTextField kotatxt;
    private javax.swing.JTextField kotatxt1;
    private javax.swing.JRadioButton lkbutton;
    private javax.swing.JTextField namatxt;
    private javax.swing.JTextField namatxt1;
    private javax.swing.JTextField nohptxt;
    private javax.swing.JTextField nohptxt1;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JTextField passwordtxt1;
    private javax.swing.JRadioButton prbutton;
    private javax.swing.JComboBox<String> provinsitxt;
    private javax.swing.JTextField provinsitxt1;
    private javax.swing.JTextField ttltxt;
    private javax.swing.JTextField ttltxt1;
    private javax.swing.JTextField usernametxt;
    private javax.swing.JTextField usernametxt1;
    // End of variables declaration//GEN-END:variables
}
