package view;

import view.daftarBaru;
import Model.koneksi;
import Model.user_model;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Wien Nurul Dewani
 */
public class daftarBaru extends javax.swing.JPanel {
menu menu = new menu();
daftarBaru daftar= new daftarBaru();
    /**
     * Creates new form daftar3
     */
    public daftarBaru() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernametxt1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buttonDaftar1 = new javax.swing.JButton();
        namatxt1 = new javax.swing.JTextField();
        buttonInputData2 = new javax.swing.JButton();
        emailtxt1 = new javax.swing.JTextField();
        nohptxt1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ttltxt1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamattxt1 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        kotatxt1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        provinsitxt1 = new javax.swing.JTextField();
        jktxt = new javax.swing.JTextField();
        kolomPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 505));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernametxt1.setToolTipText("");
        usernametxt1.setSelectionColor(new java.awt.Color(150, 203, 61));
        add(usernametxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 175, 25));

        jLabel13.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel13.setText("Email");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel14.setText("No. Telp");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        buttonDaftar1.setBackground(new java.awt.Color(255, 255, 255));
        buttonDaftar1.setText("Daftar");
        buttonDaftar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDaftar1ActionPerformed(evt);
            }
        });
        add(buttonDaftar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 103, -1));

        namatxt1.setToolTipText("");
        namatxt1.setSelectionColor(new java.awt.Color(150, 203, 61));
        add(namatxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 170, 30));

        buttonInputData2.setBackground(new java.awt.Color(255, 255, 255));
        buttonInputData2.setText("Batal");
        buttonInputData2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInputData2ActionPerformed(evt);
            }
        });
        add(buttonInputData2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 103, -1));

        emailtxt1.setToolTipText("");
        emailtxt1.setSelectionColor(new java.awt.Color(150, 203, 61));
        add(emailtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 170, 30));

        nohptxt1.setToolTipText("");
        nohptxt1.setSelectionColor(new java.awt.Color(150, 203, 61));
        add(nohptxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 175, 31));

        jLabel15.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel15.setText("Jenis Kelamin");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel16.setText("Alamat Lengkap");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jLabel17.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel17.setText("Tempat, Tanggal Lahir");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        ttltxt1.setToolTipText("");
        ttltxt1.setSelectionColor(new java.awt.Color(150, 203, 61));
        add(ttltxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 170, 30));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        alamattxt1.setColumns(20);
        alamattxt1.setRows(5);
        alamattxt1.setTabSize(5);
        alamattxt1.setSelectionColor(new java.awt.Color(150, 203, 61));
        jScrollPane2.setViewportView(alamattxt1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 170, 120));

        jLabel18.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel18.setText("Provinsi");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel19.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel19.setText("Kota");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        kotatxt1.setToolTipText("");
        kotatxt1.setSelectionColor(new java.awt.Color(150, 203, 61));
        add(kotatxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 170, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 674, -1));

        jLabel20.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel20.setText("Username");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 325, 70, 30));

        jLabel21.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel21.setText("Password");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 380, 60, 20));

        jLabel3.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel3.setText("Nama");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        provinsitxt1.setSelectionColor(new java.awt.Color(150, 203, 61));
        add(provinsitxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 170, 30));

        jktxt.setSelectionColor(new java.awt.Color(150, 203, 61));
        add(jktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 170, 30));

        kolomPassword.setToolTipText("");
        kolomPassword.setPreferredSize(new java.awt.Dimension(3, 18));
        kolomPassword.setSelectionColor(new java.awt.Color(150, 203, 61));
        add(kolomPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 174, 24));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 900, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDaftar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDaftar1ActionPerformed
        // TODO add your handling code here:
        menu menu = new menu();
        user_model us = new user_model();
        us.setNama(namatxt1.getText());
        us.setUsername(usernametxt1.getText());
        us.setPassword(kolomPassword.getText());
        us.setAlamat(alamattxt1.getText());
        us.setEmail(emailtxt1.getText());
        us.setJeniskelamin(jktxt.getText());
        us.setProvinsi(provinsitxt1.getText());
        us.setTtl(ttltxt1.getText());
        us.setKota(kotatxt1.getText());
        us.setNohp(nohptxt1.getText());

        try {
            String sql = "INSERT INTO `user baru`(`username`, `password`, `no hp`, `alamat`, `nama`, `provinsi`, `kota`, `email`, `jenis kelamin`, `ttl`) VALUES ('" + us.getNama()
                    + "','" + us.getPassword() + "','" + us.getNohp() + "','" + us.getAlamat() + "','" + us.getNama() + "','" + us.getProvinsi()
                    + "','" + us.getKota() + "','" + us.getEmail() + "','" + us.getJeniskelamin() + "','" + us.getTtl() + "')";
            java.sql.Connection conn = (Connection) koneksi.connectDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Anda telah terdaftar");

        } catch (Exception e) {

        }

//        dispose();

       menu.setVisible(true);
        JOptionPane.showMessageDialog(null, "DAFTAR BERHASIL,SILAHKAN PESAN");
        
        
    }//GEN-LAST:event_buttonDaftar1ActionPerformed

    private void buttonInputData2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInputData2ActionPerformed
        // TODO add your handling code here:
       // daftar.SetVisible(false);
    }//GEN-LAST:event_buttonInputData2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftarBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftarBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftarBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftarBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftarBaru().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamattxt1;
    private javax.swing.JButton buttonDaftar1;
    private javax.swing.JButton buttonInputData2;
    private javax.swing.JTextField emailtxt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jktxt;
    private javax.swing.JPasswordField kolomPassword;
    private javax.swing.JTextField kotatxt1;
    private javax.swing.JTextField namatxt1;
    private javax.swing.JTextField nohptxt1;
    private javax.swing.JTextField provinsitxt1;
    private javax.swing.JTextField ttltxt1;
    private javax.swing.JTextField usernametxt1;
    // End of variables declaration//GEN-END:variables

   
}
