/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author NB HP PAVILION
 */
public class HalamanAwal extends javax.swing.JFrame {
menu menu;
daftarBaru daftar;
 GridBagLayout Layout = new GridBagLayout();
 
    public HalamanAwal() {
        initComponents();
        menu = new menu();
        daftar = new daftarBaru();
        panelPindah.setVisible(true);
      panelPindah.setLayout(Layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        panelPindah.add(menu,c);
        c.gridx = 0;
        c.gridy = 0;
        panelPindah.add(daftar,c);
        menu.setVisible(false);
        daftar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tombolPesan1 = new javax.swing.JLabel();
        panelPindah = new javax.swing.JPanel();
        tombolPesan = new javax.swing.JLabel();
        tombolTentangKami = new javax.swing.JLabel();
        tombolDaftar = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tombolPesan1.setBackground(new java.awt.Color(255, 255, 255));
        tombolPesan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pesan.png"))); // NOI18N
        tombolPesan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolPesan1.setOpaque(true);
        getContentPane().add(tombolPesan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        panelPindah.setOpaque(false);
        getContentPane().add(panelPindah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 900, 510));

        tombolPesan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tombolPesan.setForeground(new java.awt.Color(255, 255, 255));
        tombolPesan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pesan2.png"))); // NOI18N
        tombolPesan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolPesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolPesanMouseClicked(evt);
            }
        });
        getContentPane().add(tombolPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 100, 40));

        tombolTentangKami.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tentangKami.png"))); // NOI18N
        tombolTentangKami.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(tombolTentangKami, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 39, -1, 40));

        tombolDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/daftar.png"))); // NOI18N
        tombolDaftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolDaftarMouseClicked(evt);
            }
        });
        getContentPane().add(tombolDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, 40));
        tombolDaftar.getAccessibleContext().setAccessibleDescription("");

        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 16, 130, 80));

        close.setBackground(new java.awt.Color(51, 51, 51));
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("X");
        close.setBorder(null);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/awal.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolPesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolPesanMouseClicked
        // TODO add your handling code here:
        menu.setVisible(true);
        daftar.setVisible(false);
        tombolPesan1.setVisible(false);
    }//GEN-LAST:event_tombolPesanMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        close.setBackground(Color.red);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        close.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_closeMouseExited

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
   
    }//GEN-LAST:event_closeActionPerformed

    private void tombolDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolDaftarMouseClicked
        // TODO add your handling code here:
        daftar.setVisible(true);
        menu.setVisible(false);
         tombolPesan1.setVisible(false);
    }//GEN-LAST:event_tombolDaftarMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        daftar.setVisible(false);
        menu.setVisible(false);
         tombolPesan1.setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanAwal().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton close;
    private javax.swing.JLabel home;
    private javax.swing.JPanel panelPindah;
    private javax.swing.JLabel tombolDaftar;
    private javax.swing.JLabel tombolPesan;
    private javax.swing.JLabel tombolPesan1;
    private javax.swing.JLabel tombolTentangKami;
    // End of variables declaration//GEN-END:variables
}
