  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.*;
import java.sql.Connection;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WINDOWS 10
 */
public class Menu extends javax.swing.JFrame {

     private DefaultTableModel mdl = new DefaultTableModel();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        mdl.addColumn("Nama");
        mdl.addColumn("Harga");
        mdl.addColumn("Waktu");
        mdl.addColumn("jumlah");
        //Proses SetModel
        TableOrder.setModel(mdl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gmbrtomat = new javax.swing.JLabel();
        gmbrkubis = new javax.swing.JLabel();
        gmbrkangkung = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gmbrterong = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Kubistxt = new javax.swing.JButton();
        Kangkungtxt = new javax.swing.JButton();
        Cabaitxt = new javax.swing.JButton();
        KacangPanjangtxt = new javax.swing.JButton();
        Terongtxt = new javax.swing.JButton();
        Tomattxt = new javax.swing.JButton();
        Buncistxt = new javax.swing.JButton();
        Worteltxt = new javax.swing.JButton();
        Timuntxt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableOrder = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        hargaKubis = new javax.swing.JLabel();
        hargaKangkung = new javax.swing.JLabel();
        hargaCabai = new javax.swing.JLabel();
        hargaKacangPanjang = new javax.swing.JLabel();
        hargaTerong = new javax.swing.JLabel();
        hargaTomat = new javax.swing.JLabel();
        hargaBuncis = new javax.swing.JLabel();
        hargaWortel = new javax.swing.JLabel();
        hargaTimun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gmbrtomat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/tomat.png"))); // NOI18N
        jPanel1.add(gmbrtomat, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 90, 100));

        gmbrkubis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/kubis.png"))); // NOI18N
        jPanel1.add(gmbrkubis, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 90, 100));

        gmbrkangkung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/kangkung.png"))); // NOI18N
        jPanel1.add(gmbrkangkung, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 90, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/tauge.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 100, 90));

        gmbrterong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/terong.png"))); // NOI18N
        jPanel1.add(gmbrterong, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 90, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/wortel.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 90, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/cabai.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 90, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/buncis.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 100, 90));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/timun.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, -1, 90));

        Kubistxt.setText("Kubis");
        Kubistxt.setPreferredSize(new java.awt.Dimension(50, 50));
        Kubistxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KubistxtActionPerformed(evt);
            }
        });
        jPanel1.add(Kubistxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 69, 88, 81));

        Kangkungtxt.setBackground(new java.awt.Color(255, 255, 255));
        Kangkungtxt.setText("kangkung");
        Kangkungtxt.setAlignmentY(0.0F);
        Kangkungtxt.setIconTextGap(0);
        Kangkungtxt.setOpaque(false);
        Kangkungtxt.setPreferredSize(new java.awt.Dimension(50, 50));
        Kangkungtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KangkungtxtActionPerformed(evt);
            }
        });
        jPanel1.add(Kangkungtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 73, 80, 80));

        Cabaitxt.setPreferredSize(new java.awt.Dimension(50, 50));
        Cabaitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CabaitxtActionPerformed(evt);
            }
        });
        jPanel1.add(Cabaitxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 88, 81));

        KacangPanjangtxt.setText("Toge");
        KacangPanjangtxt.setPreferredSize(new java.awt.Dimension(50, 50));
        KacangPanjangtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KacangPanjangtxtActionPerformed(evt);
            }
        });
        jPanel1.add(KacangPanjangtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 231, 80, 70));

        Terongtxt.setText("Terong");
        Terongtxt.setPreferredSize(new java.awt.Dimension(50, 50));
        Terongtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerongtxtActionPerformed(evt);
            }
        });
        jPanel1.add(Terongtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 221, 80, 80));

        Tomattxt.setText("Tomat");
        Tomattxt.setPreferredSize(new java.awt.Dimension(50, 50));
        Tomattxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TomattxtActionPerformed(evt);
            }
        });
        jPanel1.add(Tomattxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 80, 80));

        Buncistxt.setText("Buncis");
        Buncistxt.setPreferredSize(new java.awt.Dimension(50, 50));
        Buncistxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuncistxtActionPerformed(evt);
            }
        });
        jPanel1.add(Buncistxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 88, 81));

        Worteltxt.setText("Wortel");
        Worteltxt.setPreferredSize(new java.awt.Dimension(50, 50));
        Worteltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorteltxtActionPerformed(evt);
            }
        });
        jPanel1.add(Worteltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 88, 81));

        Timuntxt.setText("Timun");
        Timuntxt.setPreferredSize(new java.awt.Dimension(50, 50));
        Timuntxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimuntxtActionPerformed(evt);
            }
        });
        jPanel1.add(Timuntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 88, 81));

        TableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Harga", "Jumlah", "Total"
            }
        ));
        jScrollPane1.setViewportView(TableOrder);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 67, 377, 373));

        jButton1.setText("Submit");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 524, 377, -1));

        hargaKubis.setText("3000");
        jPanel1.add(hargaKubis, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 156, -1, -1));

        hargaKangkung.setText("3000");
        jPanel1.add(hargaKangkung, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 156, -1, -1));

        hargaCabai.setText("12000");
        jPanel1.add(hargaCabai, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 156, -1, -1));

        hargaKacangPanjang.setText("2000");
        jPanel1.add(hargaKacangPanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        hargaTerong.setText("2500");
        jPanel1.add(hargaTerong, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        hargaTomat.setText("6000");
        jPanel1.add(hargaTomat, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, -1, -1));

        hargaBuncis.setText("7000");
        jPanel1.add(hargaBuncis, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        hargaWortel.setText("7500");
        jPanel1.add(hargaWortel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, -1, -1));

        hargaTimun.setText("2500");
        jPanel1.add(hargaTimun, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TimuntxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimuntxtActionPerformed
        Calendar c1 = Calendar.getInstance(); 
        Date dateOne = c1.getTime();
        
        order_model or = new order_model();
        or.setNamaSayur(Timuntxt.getText());
        or.setHargaSayur(hargaTimun.getText());
        
        String a = Timuntxt.getText();
        String b = hargaTimun.getText();
        int jumlah;
        String input;
        input = JOptionPane.showInputDialog("Masukkan jumlah : ");
        jumlah = Integer.parseInt(input);
        Date c = dateOne;
        Object[] x = {a, b, c, input};
        mdl.addRow(x);
        
            try {
            String sql = "INSERT INTO `data sayur` (`Nama`, `Harga`,`Waktu`) VALUES ('" +or.getNamaSayur()+ "','" + or.getHargaSayur()+ "','" +dateOne+ "')";
            java.sql.Connection conn = (Connection) koneksi.connectDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
           
         
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_TimuntxtActionPerformed

    private void WorteltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorteltxtActionPerformed
        Calendar c1 = Calendar.getInstance(); 
        Date dateOne = c1.getTime(); 
        
        order_model or = new order_model();
        or.setNamaSayur(Worteltxt.getText());
        or.setHargaSayur(hargaWortel.getText());
        
        String a = Worteltxt.getText();
        String b = hargaWortel.getText();
        
        int jumlah;
        String input;
        input = JOptionPane.showInputDialog("Masukkan jumlah : ");
        jumlah = Integer.parseInt(input);
        
        Date c = dateOne;
        Object[] x = {a, b, c};
        mdl.addRow(x);
        
        try {
            String sql = "INSERT INTO `data sayur` (`Nama`, `Harga`,`Waktu`) VALUES ('" +or.getNamaSayur()+ "','" + or.getHargaSayur()+ "','" +dateOne+ "')";
            java.sql.Connection conn = (Connection) koneksi.connectDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
           
         
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_WorteltxtActionPerformed

    private void BuncistxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuncistxtActionPerformed
        Calendar c1 = Calendar.getInstance(); 
        Date dateOne = c1.getTime(); 
        
        order_model or = new order_model();
        or.setNamaSayur(Buncistxt.getText());
        or.setHargaSayur(hargaBuncis.getText());
        
        String a = Buncistxt.getText();
        String b = hargaBuncis.getText();
        
        int jumlah;
        String input;
        input = JOptionPane.showInputDialog("Masukkan jumlah : ");
        jumlah = Integer.parseInt(input);
        
        Date c = dateOne;
        Object[] x = {a, b, c};
        mdl.addRow(x);
        try {
            String sql = "INSERT INTO `data sayur` (`Nama`, `Harga`,`Waktu`) VALUES ('" +or.getNamaSayur()+ "','" + or.getHargaSayur()+ "','" +dateOne+ "')";
            java.sql.Connection conn = (Connection) koneksi.connectDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
           
         
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_BuncistxtActionPerformed

    private void TomattxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TomattxtActionPerformed
        Calendar c1 = Calendar.getInstance(); 
        Date dateOne = c1.getTime(); 
        
        order_model or = new order_model();
        or.setNamaSayur(Tomattxt.getText());
        or.setHargaSayur(hargaTomat.getText());
        
        String a = Tomattxt.getText();
        String b = hargaTomat.getText();
        
        int jumlah;
        String input;
        input = JOptionPane.showInputDialog("Masukkan jumlah : ");
        jumlah = Integer.parseInt(input);
        
        Date c = dateOne;
        Object[] x = {a, b, c};
        mdl.addRow(x);
        try {
            String sql = "INSERT INTO `data sayur` (`Nama`, `Harga`,`Waktu`) VALUES ('" +or.getNamaSayur()+ "','" + or.getHargaSayur()+ "','" +dateOne+ "')";
            java.sql.Connection conn = (Connection) koneksi.connectDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
           
         
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_TomattxtActionPerformed

    private void TerongtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerongtxtActionPerformed
        Calendar c1 = Calendar.getInstance(); 
        Date dateOne = c1.getTime(); 
        
        order_model or = new order_model();
        or.setNamaSayur(Terongtxt.getText());
        or.setHargaSayur(hargaTerong.getText());
        
        String a = Terongtxt.getText();
        String b = hargaTerong.getText();
        
        int jumlah;
        String input;
        input = JOptionPane.showInputDialog("Masukkan jumlah : ");
        jumlah = Integer.parseInt(input);
        
        Date c = dateOne;
        Object[] x = {a, b, c};
        mdl.addRow(x);
        try {
            String sql = "INSERT INTO `data sayur` (`Nama`, `Harga`,`Waktu`) VALUES ('" +or.getNamaSayur()+ "','" + or.getHargaSayur()+ "','" +dateOne+ "')";
            java.sql.Connection conn = (Connection) koneksi.connectDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
           
         
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_TerongtxtActionPerformed

    private void KacangPanjangtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KacangPanjangtxtActionPerformed
        Calendar c1 = Calendar.getInstance(); 
        Date dateOne = c1.getTime(); 
        
        order_model or = new order_model();
        or.setNamaSayur(KacangPanjangtxt.getText());
        or.setHargaSayur(hargaKacangPanjang.getText());
        
        String a = KacangPanjangtxt.getText();
        String b = hargaKacangPanjang.getText();
        
        int jumlah;
        String input;
        input = JOptionPane.showInputDialog("Masukkan jumlah : ");
        jumlah = Integer.parseInt(input);
        
        Date c = dateOne;
        Object[] x = {a, b, c};
        mdl.addRow(x);
<<<<<<< HEAD
       try {
            String sql = "INSERT INTO `data sayur` (`Nama`, `Harga`,`Waktu`) VALUES ('" +KacangPanjangtxt.getText()+ "','" + hargaKacangPanjang.getText()+ "','" +dateOne+ "')";
=======
        try {
            String sql = "INSERT INTO `data sayur` (`Nama`, `Harga`,`Waktu`) VALUES ('" +or.getNamaSayur()+ "','" + or.getHargaSayur()+ "','" +dateOne+ "')";
>>>>>>> 8d7d5824e9b21d34995ebaa0f5d063282d15f188
            java.sql.Connection conn = (Connection) koneksi.connectDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
           
         
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_KacangPanjangtxtActionPerformed

    private void CabaitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CabaitxtActionPerformed
        Calendar c1 = Calendar.getInstance(); 
        Date dateOne = c1.getTime(); 
        
        order_model or = new order_model();
        or.setNamaSayur(Cabaitxt.getText());
        or.setHargaSayur(hargaCabai.getText());
        
        String a = Cabaitxt.getText();
        String b = hargaCabai.getText();
        
        int jumlah;
        String input;
        input = JOptionPane.showInputDialog("Masukkan jumlah : ");
        jumlah = Integer.parseInt(input);
        
        Date c = dateOne;
        Object[] x = {a, b, c};
        mdl.addRow(x); 
        try {
            String sql = "INSERT INTO `data sayur` (`Nama`, `Harga`,`Waktu`) VALUES ('" +or.getNamaSayur()+ "','" + or.getHargaSayur()+ "','" +dateOne+ "')";
            java.sql.Connection conn = (Connection) koneksi.connectDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
           
         
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_CabaitxtActionPerformed

    private void KangkungtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KangkungtxtActionPerformed
        Calendar c1 = Calendar.getInstance(); 
        Date dateOne = c1.getTime(); 
        
        order_model or = new order_model();
        or.setNamaSayur(Kangkungtxt.getText());
        or.setHargaSayur(hargaKangkung.getText());
        
        String a = Kangkungtxt.getText();
        String b = hargaKangkung.getText();
        
        int jumlah;
        String input;
        input = JOptionPane.showInputDialog("Masukkan jumlah : ");
        jumlah = Integer.parseInt(input);
        
        Date c = dateOne;
        Object[] x = {a, b, c};
        mdl.addRow(x);
        try {
            String sql = "INSERT INTO `data sayur` (`Nama`, `Harga`,`Waktu`) VALUES ('" +or.getNamaSayur()+ "','" + or.getHargaSayur()+ "','" +dateOne+ "')";
            java.sql.Connection conn = (Connection) koneksi.connectDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
           
         
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_KangkungtxtActionPerformed

    private void KubistxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KubistxtActionPerformed
        Calendar c1 = Calendar.getInstance(); 
        Date dateOne = c1.getTime(); 
        
        order_model or = new order_model();
        or.setNamaSayur(Kubistxt.getText());
        or.setHargaSayur(hargaKubis.getText());
        
        String a = Kubistxt.getText();
        String b = hargaKubis.getText();
        
        int jumlah;
        String input;
        input = JOptionPane.showInputDialog("Masukkan jumlah : ");
        jumlah = Integer.parseInt(input);
        
        Date c = dateOne;
        Object[] x = {a, b, c};
        mdl.addRow(x);
        try {
            String sql = "INSERT INTO `data sayur` (`Nama`, `Harga`,`Waktu`) VALUES ('" +or.getNamaSayur()+ "','" + or.getHargaSayur()+ "','" +dateOne+ "')";
            java.sql.Connection conn = (Connection) koneksi.connectDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
           
         
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_KubistxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buncistxt;
    private javax.swing.JButton Cabaitxt;
    private javax.swing.JButton KacangPanjangtxt;
    private javax.swing.JButton Kangkungtxt;
    private javax.swing.JButton Kubistxt;
    private javax.swing.JTable TableOrder;
    private javax.swing.JButton Terongtxt;
    private javax.swing.JButton Timuntxt;
    private javax.swing.JButton Tomattxt;
    private javax.swing.JButton Worteltxt;
    private javax.swing.JLabel gmbrkangkung;
    private javax.swing.JLabel gmbrkubis;
    private javax.swing.JLabel gmbrterong;
    private javax.swing.JLabel gmbrtomat;
    private javax.swing.JLabel hargaBuncis;
    private javax.swing.JLabel hargaCabai;
    private javax.swing.JLabel hargaKacangPanjang;
    private javax.swing.JLabel hargaKangkung;
    private javax.swing.JLabel hargaKubis;
    private javax.swing.JLabel hargaTerong;
    private javax.swing.JLabel hargaTimun;
    private javax.swing.JLabel hargaTomat;
    private javax.swing.JLabel hargaWortel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
